from __future__ import annotations

from typing import NamedTuple, Protocol

import numpy as np
from scipy.sparse import csr_matrix


class UFLExpression(Protocol):
    """Structural type for the symbolic UFL algebra used in local form builders."""

    def __add__(self, other: object, /) -> UFLExpression: ...
    def __radd__(self, other: object, /) -> UFLExpression: ...
    def __sub__(self, other: object, /) -> UFLExpression: ...
    def __rsub__(self, other: object, /) -> UFLExpression: ...
    def __mul__(self, other: object, /) -> UFLExpression: ...
    def __rmul__(self, other: object, /) -> UFLExpression: ...
    def __truediv__(self, other: object, /) -> UFLExpression: ...
    def __rtruediv__(self, other: object, /) -> UFLExpression: ...
    def __neg__(self) -> UFLExpression: ...
    def __call__(self, restriction: str, /) -> UFLExpression: ...


class UFLAlgebra(Protocol):
    """Subset of the UFL module operations needed by the USFEM weak form."""

    def grad(self, expression: UFLExpression, /) -> UFLExpression: ...
    def div(self, expression: UFLExpression, /) -> UFLExpression: ...
    def inner(
        self,
        left: UFLExpression,
        right: UFLExpression,
        /,
    ) -> UFLExpression: ...
    def jump(self, expression: UFLExpression, /) -> UFLExpression: ...
    def gt(self, left: UFLExpression, right: UFLExpression, /) -> UFLExpression: ...
    def conditional(
        self,
        condition: UFLExpression,
        true_value: UFLExpression,
        false_value: UFLExpression,
        /,
    ) -> UFLExpression: ...
    def max_value(
        self,
        left: UFLExpression,
        right: UFLExpression,
        /,
    ) -> UFLExpression: ...
    def sqrt(self, expression: UFLExpression, /) -> UFLExpression: ...
    def tanh(self, expression: UFLExpression, /) -> UFLExpression: ...
    def CellDiameter(self, domain: object, /) -> UFLExpression: ...
    def avg(self, expression: UFLExpression, /) -> UFLExpression: ...
    def TrialFunction(self, space: object, /) -> UFLExpression: ...
    def TestFunction(self, space: object, /) -> UFLExpression: ...


class FEMFunctionVector(Protocol):
    array: np.ndarray

    def scatter_forward(self) -> None: ...


class FEMFunction(Protocol):
    x: FEMFunctionVector


class PETScCSRMatrix(Protocol):
    def getValuesCSR(self) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
    def getSize(self) -> tuple[int, int]: ...


class PETScCSRConvertible(Protocol):
    def assemble(self) -> None: ...
    def convert(self, matrix_type: str, /) -> PETScCSRMatrix: ...


class USFEMBlockCSRSystem(NamedTuple):
    a00: csr_matrix
    a01: csr_matrix
    a10: csr_matrix
    a11: csr_matrix
    rhs: np.ndarray
